CREATE TABLE DEPARTMENT (
    DEPT_CODE	VARCHAR(4)	NOT NULL,
    DEPT_NAME	VARCHAR(15)	NOT NULL,
    DEPT_LOC	VARCHAR(15),
    PRIMARY KEY (DEPT_CODE)
);

CREATE TABLE EMP_ROLE (
    EMP_RCODE	VARCHAR(4)	NOT NULL,
    EMP_RNAME	VARCHAR(15)	NOT NULL,
    PRIMARY KEY (EMP_RCODE)
);

CREATE TABLE EMPLOYEE (
    EMP_CODE	VARCHAR(4)	NOT NULL,
    EMP_NAME	VARCHAR(12)	NOT NULL,
    EMP_MGT 	VARCHAR(4),
    EMP_SAL		INTEGER	NOT NULL,
    EMP_RCODE	VARCHAR(4)	NOT NULL,
    PRIMARY KEY (EMP_CODE),
    FOREIGN KEY (EMP_RCODE) REFERENCES EMP_ROLE(EMP_RCODE)
);

CREATE TABLE REL_DEPARTMENT (
    RD_EMP_CODE	VARCHAR(4)	NOT NULL,
    RD_DEPT_CODE	VARCHAR(4)	NOT NULL,
    PRIMARY KEY (RD_EMP_CODE, RD_DEPT_CODE),
    FOREIGN KEY(RD_EMP_CODE) REFERENCES EMPLOYEE(EMP_CODE),
    FOREIGN KEY(RD_DEPT_CODE) REFERENCES DEPARTMENT(DEPT_CODE)
);

CREATE TABLE MOVIE (
    MOV_CODE	VARCHAR(5)	NOT NULL,
    MOV_NAME	VARCHAR(30)	NOT NULL,
    MOV_MPAA	VARCHAR(2)	NOT NULL,
    MOV_PDDATE	DATE		NOT NULL,
    MOV_OPDATE	DATE,		
    PRIMARY KEY (MOV_CODE)
);

CREATE TABLE DRAMA (
    DRM_CODE	VARCHAR(5)	NOT NULL,
    DRM_NAME	VARCHAR(30)	NOT NULL,
    DRM_PRD		VARCHAR(5)	NOT NULL,
    DRM_BRD		VARCHAR(3)	NOT NULL,
    DRM_OPDATE	DATE,
    PRIMARY KEY (DRM_CODE)
);

CREATE TABLE MUSIC (
    MSC_CODE	VARCHAR(5)	NOT NULL,
    MSC_NAME	VARCHAR(30)	NOT NULL,
    MSC_DATE		DATE		NOT NULL,
    MSC_PRICE	INTEGER		NOT NULL,
    MSC_CSF		VARCHAR(6) 	NOT NULL CHECK (MSC_CSF IN ('싱글', '정규')),
    PRIMARY KEY (MSC_CODE)
);

CREATE TABLE PART_MOVIE (
    PM_MOV_CODE	VARCHAR(5)	NOT NULL,
    PM_EMP_CODE		VARCHAR(4)	NOT NULL,
    PM_EMP_ROLE		VARCHAR(6)	NOT NULL CHECK (PM_EMP_ROLE IN ('주연', '조연', '단역')),
    PM_MOV_FEE		INTEGER,
    PRIMARY KEY (PM_MOV_CODE, PM_EMP_CODE), 
    FOREIGN KEY (PM_MOV_CODE) REFERENCES MOVIE(MOV_CODE),
    FOREIGN KEY (PM_EMP_CODE) REFERENCES EMPLOYEE(EMP_CODE)
);

CREATE TABLE PART_DRAMA (
    PD_DRM_CODE		VARCHAR(5)	NOT NULL,
    PD_EMP_CODE		VARCHAR(4)	NOT NULL,
    PD_EMP_ROLE		VARCHAR(6)	NOT NULL CHECK (PD_EMP_ROLE IN ('주연', '조연', '단역')),
    PD_EMP_FEE		INTEGER,
    PRIMARY KEY (PD_DRM_CODE, PD_EMP_CODE),
    FOREIGN KEY (PD_DRM_CODE) REFERENCES DRAMA(DRM_CODE),
    FOREIGN KEY (PD_EMP_CODE) REFERENCES EMPLOYEE(EMP_CODE)
);

CREATE TABLE PART_MUSIC (
    PM_MSC_CODE		VARCHAR(5)	NOT NULL,
    PM_EMP_CODE		VARCHAR(4)	NOT NULL,
    PM_EMP_ROLE		VARCHAR(9)	NOT NULL CHECK (PM_EMP_ROLE IN ('메인', '피처링')),
    PM_EMP_FEE		INTEGER,
    PRIMARY KEY (PM_MSC_CODE),
    FOREIGN KEY (PM_MSC_CODE) REFERENCES MUSIC(MSC_CODE),
    FOREIGN KEY (PM_EMP_CODE) REFERENCES EMPLOYEE(EMP_CODE)
);
