DROP TABLE IF EXISTS REL_DEPARTMENT;
DROP TABLE IF EXISTS DEPARTMENT;

DROP TABLE IF EXISTS PART_MOVIE;
DROP TABLE IF EXISTS PART_MUSIC;
DROP TABLE IF EXISTS PART_DRAMA;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS EMP_ROLE;

DROP TABLE IF EXISTS MOVIE;
DROP TABLE IF EXISTS DRAMA;
DROP TABLE IF EXISTS MUSIC;